# Generated by Django 5.2.4 on 2025-07-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hoteldata", "0002_hotel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hotel",
            name="index",
        ),
        migrations.AddField(
            model_name="hotel",
            name="code",
            field=models.CharField(
                db_comment="Combines with city abbreviation to create the hotel identifier.",
                default="___",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="hotel",
            constraint=models.UniqueConstraint(
                fields=("city", "code"), name="hotel identifier"
            ),
        ),
    ]
